debug: false
server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PW}
    url: ${DB_URL}
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

admin:
  user: ${ADMIN_USER}
  password: ${ADMIN_PASSWORD}
