debug: false
server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gadget-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: sa
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

admin:
  user: ${ADMIN_USER}
  password: ${ADMIN_PASSWORD}
