# on push to main -
# Checkout src-code
# Build JAR
# Create docker image (amd64)
# Sign in to Artifact Registry and Docker?
# Upload image to Artifact Reg
#

name: Build and deploy JAR to GCP

on:
  push:
    branches:
      - main
env:
  IMAGE_URL: eu.gcr.io/saltjokes-385809/saltjokes-repo/jokes:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
#      - name: Run tests
#        run: ./gradlew test
      - name: Build jar
#        if: success()
        run: ./gradlew bootJar

      - name: Docker Build
        run: docker build -t $IMAGE_URL .
      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
#          project_id: saltjokes-385809
          credentials_json: ${{ env.GCP_SA_KEY }}
#          export_default_credentials: true
      - name: Setup Docker For GCP
        run: |
          gcloud auth configure-docker -q
      - name: Docker Push
        run: docker push $IMAGE_URL
