on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK and Gradle
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build
        run: gradle build
      - name: Get Coverage
        uses: codecov/codecov-action@v3
  
