name: Gradle Spring Boot Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK and Gradle
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Run tests
      run: ./gradlew test
    - name: Build jar
      if: success()
      run: ./gradlew bootJar
    - name: Upload jar
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: build/libs/DeveloperJokesApp-0.0.1-SNAPSHOT.jar
