name: Gradle Spring Boot Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17 and Gradle
      uses: Adoptium/setup-gradle@v1
      with:
        java-version: 17
        gradle-version: '7.2'
    - name: Run tests
      run: ./gradlew test
    - name: Build jar
      if: success()
      run: ./gradlew bootJar
    - name: Upload jar
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: My Application
        path: build/libs/DeveloperJokesApp-0.0.1-SNAPSHOT.jar
